name: 'Submit Chunk to Internet Archive'
description: 'Submits a batch of URLs to the Internet Archive'

inputs:
  url-chunk:
    description: 'JSON array of URLs to submit'
    required: true
  # ia-access-key:
  #   description: "Internet Archive Access Key"
  #   required: true
  # ia-secret-key:
  #   description: "Internet Archive Secret Key"
  #   required: true

runs:
  using: 'node24'
  main: 'index.ts'
